---
language: python
python: "2.7"
sudo: true

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install git+https://github.com/ansible/ansible.git
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -c local -vvv
  - >
    ansible-playbook tests/test.yml -i tests/inventory -c local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - exec $SHELL -l
  - command fzf

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
